### ISSUE TITLE
integrated_gradients.py  is not complete

### ISSUE THREAD

**Issue by neouyghur** [tensorflow/saliency#2]
Hi, GetSmoothedMask function is not given at integrated_gradients.py.

**Comment by experiencor** [comment]
I think that GetSmoothedMask is defined in the superclass SaliencyMask. GetSmoothedMask is automatically obtained by applying GetMask on many noisy versions of the input image and taking the average in the end.

**Comment by nsthorat** [comment]
@experiencor is right, GetSmoothedMask simply calls GetMask by adding noise several times and averaging. This is agnostic of the specific technique, so can live on the base class.
